(function(){
  "use strict";
  let state=window.GanState.load();
  const toast=document.getElementById("adminToast");
  const showToast=message=>{toast.textContent=message;toast.classList.add("show");clearTimeout(window.adminToastTimer);window.adminToastTimer=setTimeout(()=>toast.classList.remove("show"),2200)};
  const values=form=>Object.fromEntries(new FormData(form).entries());

  document.querySelectorAll(".admin-tab").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".admin-tab").forEach(item=>item.classList.toggle("active",item===button));document.querySelectorAll(".admin-panel").forEach(panel=>panel.classList.toggle("active",panel.dataset.adminPanel===button.dataset.adminTarget));window.scrollTo({top:0,behavior:"smooth"})}));

  const todayForm=document.getElementById("todayForm");
  function fillToday(){const h=state.home,f=todayForm.elements;f.morningName1.value=h.morning[0].name;f.morningRole1.value=h.morning[0].role;f.morningName2.value=h.morning[1].name;f.morningRole2.value=h.morning[1].role;f.afternoonName1.value=h.afternoon[0].name;f.afternoonRole1.value=h.afternoon[0].role;f.afternoonName2.value=h.afternoon[1].name;f.afternoonRole2.value=h.afternoon[1].role;f.meetingTitle.value=h.meetingTitle;f.meetingDetails.value=h.meetingDetails;f.activityTitle.value=h.activityTitle;f.reminder.value=h.reminder;f.shabbat1.value=h.shabbat[0].name;f.shabbat2.value=h.shabbat[1].name}
  todayForm.addEventListener("submit",event=>{event.preventDefault();const v=values(todayForm);state.home={...state.home,updatedAt:new Intl.DateTimeFormat("he-IL",{hour:"2-digit",minute:"2-digit"}).format(new Date()),morning:[{...state.home.morning[0],name:v.morningName1,role:v.morningRole1},{...state.home.morning[1],name:v.morningName2,role:v.morningRole2}],afternoon:[{...state.home.afternoon[0],name:v.afternoonName1,role:v.afternoonRole1},{...state.home.afternoon[1],name:v.afternoonName2,role:v.afternoonRole2}],meetingTitle:v.meetingTitle,meetingDetails:v.meetingDetails,activityTitle:v.activityTitle,reminder:v.reminder,shabbat:[{...state.home.shabbat[0],name:v.shabbat1},{...state.home.shabbat[1],name:v.shabbat2}]};window.GanState.save(state);showToast("עדכון היום נשמר")});

  const adminEvents=document.getElementById("adminEvents");
  function renderEvents(){adminEvents.innerHTML="";[...state.events].sort((a,b)=>a.date.localeCompare(b.date)).forEach(item=>{const row=document.createElement("div");row.className="admin-list-row";row.innerHTML=`<div><strong>${item.title}</strong><div class="meta">${item.date} · ${item.details||"ללא פרטים"}</div></div><span class="small-badge ${item.type}">${item.type==="no-kindergarten"?"אין גן":item.type==="birthday"?"יום הולדת":"אירוע"}</span><button class="danger-button" data-delete-event="${item.id}">מחיקה</button>`;adminEvents.appendChild(row)});adminEvents.querySelectorAll("[data-delete-event]").forEach(button=>button.addEventListener("click",()=>{state.events=state.events.filter(item=>item.id!==button.dataset.deleteEvent);window.GanState.save(state);renderEvents();showToast("האירוע נמחק")}))}
  document.getElementById("eventForm").addEventListener("submit",event=>{event.preventDefault();const v=values(event.currentTarget);state.events.push({id:crypto.randomUUID(),date:v.eventDate,title:v.eventTitle,details:v.eventDetails,type:v.eventType});window.GanState.save(state);event.currentTarget.reset();renderEvents();showToast("האירוע נוסף")});

  const adminAlbums=document.getElementById("adminAlbums");
  function renderAlbums(){adminAlbums.innerHTML="";state.albums.forEach(album=>{const row=document.createElement("div");row.className="admin-list-row";row.innerHTML=`<div><strong>${album.date}</strong><div class="meta">${album.photos.length} תמונות · מחיקה: ${album.expires}</div></div><span class="small-badge">${album.photos.length} תמונות</span><button class="danger-button" data-delete-album="${album.id}">מחיקה</button>`;adminAlbums.appendChild(row)});adminAlbums.querySelectorAll("[data-delete-album]").forEach(button=>button.addEventListener("click",()=>{state.albums=state.albums.filter(item=>item.id!==button.dataset.deleteAlbum);window.GanState.save(state);renderAlbums();showToast("האלבום נמחק")}))}
  document.getElementById("albumForm").addEventListener("submit",event=>{event.preventDefault();const date=event.currentTarget.elements.albumDate.value;const expires=new Date(`${date}T12:00:00`);expires.setDate(expires.getDate()+7);state.albums.unshift({id:crypto.randomUUID(),date,expires:expires.toISOString().slice(0,10),photos:["assets/album-1.svg"]});window.GanState.save(state);event.currentTarget.reset();renderAlbums();showToast("האלבום נוצר")});

  const fundForm=document.getElementById("fundForm");fundForm.elements.collected.value=state.committee.collected;fundForm.elements.paybox.value=state.committee.paybox;fundForm.addEventListener("submit",event=>{event.preventDefault();const v=values(event.currentTarget);state.committee.collected=Number(v.collected||0);state.committee.paybox=v.paybox||"";window.GanState.save(state);showToast("קופת הוועד נשמרה")});
  document.getElementById("expenseForm").addEventListener("submit",event=>{event.preventDefault();const v=values(event.currentTarget);state.committee.expenses.unshift({id:crypto.randomUUID(),description:v.description,amount:Number(v.amount),date:v.expenseDate});window.GanState.save(state);event.currentTarget.reset();showToast("ההוצאה נוספה")});

  const pollForm=document.getElementById("pollForm");pollForm.elements.pollTitle.value=state.committee.poll.title;pollForm.elements.pollOption1.value=state.committee.poll.options[0];pollForm.elements.pollOption2.value=state.committee.poll.options[1];pollForm.elements.pollActive.checked=state.committee.poll.active;pollForm.addEventListener("submit",event=>{event.preventDefault();const v=values(event.currentTarget);state.committee.poll={active:event.currentTarget.elements.pollActive.checked,title:v.pollTitle,options:[v.pollOption1,v.pollOption2]};window.GanState.save(state);showToast("הסקר נשמר")});
  const treatsForm=document.getElementById("treatsForm");treatsForm.elements.treatsTitle.value=state.committee.treats.title;treatsForm.elements.treatItems.value=state.committee.treats.items.map(item=>item.label).join("\n");treatsForm.elements.treatsActive.checked=state.committee.treats.active;treatsForm.addEventListener("submit",event=>{event.preventDefault();const v=values(event.currentTarget);state.committee.treats={active:event.currentTarget.elements.treatsActive.checked,title:v.treatsTitle,items:v.treatItems.split("\n").map(label=>label.trim()).filter(Boolean).map(label=>({label,claimedBy:""}))};window.GanState.save(state);showToast("רשימת הכיבוד נשמרה")});

  fillToday();renderEvents();renderAlbums();
})();
